from playwright.sync_api import sync_playwright, expect
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto('https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/auth/registration')
    email_input = page.get_by_test_id('registration-form-email-input').locator('input')
    email_input.fill('user.name@gmail.com')
    username_input = page.get_by_test_id('registration-form-username-input').locator('input')
    username_input.fill('username')
    password_input = page.get_by_test_id('registration-form-password-input').locator('input')
    password_input.fill('password')
    registration_button = page.get_by_test_id('registration-page-registration-button')
    expect(registration_button).to_have_text('Registration')
    registration_button.click()
    expect(page).to_have_url('https://nikita-filonov.github.io/qa-automation-engineer-ui-course/#/dashboard')
    page_title = page.get_by_test_id('dashboard-toolbar-title-text')
    expect(page_title).to_have_text('Dashboard')
    context.storage_state(path='browser-state.json')

